apiVersion: apps/v1

kind: Deployment

metadata:

  name: pega

spec:

  replicas: 1

  selector:

    matchLabels:

      app: pega

  template:

    metadata:

      labels:

        app: pega

    spec:

      containers:

        - name: pega

          image: nguthi9876/pegawebapp:871

          ports:

            - containerPort: 8080

            - containerPort: 443

          env:

            - name: DB_HOST

              value: postgres  # Service name of PostgreSQL

            - name: DB_PORT

              value: "5432"

            - name: DB_NAME

              value: postgres

            - name: DB_USER

              value: postgres

            - name: DB_PASSWORD

              value: postgres

            - name: JDBC_URL

              value: jdbc:postgresql://postgres:5432/postgres

            - name: JDBC_CLASS

              value: org.postgresql.Driver 

---

apiVersion: v1

kind: Service

metadata:

  name: pega

spec:

  selector:

    app: pega

  ports:

    - name: http

      protocol: TCP

      port: 80

      targetPort: 8080

      nodePort: 30080

    - name: https

      protocol: TCP

      port: 443

      targetPort: 443

      nodePort: 30443

  type: NodePort  # Exposes Pega outside Minikube
